((nil . ((cider-default-cljs-repl . shadow)
	 (cider-shadow-default-options . ":main")
	 (cider-shadow-watched-builds . (":main"))
	 (cider-preferred-build-tool . shadow-cljs)
	 (cider-offer-to-open-cljs-app-in-browser . nil))))
