((nil . ((clojure-indent-style . 'always-indent)
	 (cider-default-cljs-repl . shadow)
	 (cider-shadow-default-options . ":main")
	 (cider-shadow-watched-builds . (":main"))
	 (cider-preferred-build-tool . shadow-cljs))))
